### PR TITLE
Add Laravel 7 support

### PR DESCRIPTION
**Pull request by jeremykenedy**

### CODE REVIEW

**Comment by erikdonohoo** [comment]
Would love to get this merged in. This is blocking my upgrade to Laravel 7 as well

**Comment by Dolaned** [comment]
id also like this merged please

**Comment by m1guelpf** [comment]
Pushed this before realizing there was a PR for this, sorry. Anyway, this is released now!

**Comment by bumbummen99** [comment]
Thank you alot!

**Pull request closed without merging**
